# Generated by Django 4.2.4 on 2023-08-23 05:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0003_alter_post_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="tags",
            field=models.CharField(choices=[("all", "자유")], max_length=20),
        ),
    ]
