# Generated by Django 4.2.4 on 2023-08-23 05:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0004_alter_post_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="tags",
            field=models.CharField(
                choices=[("all", "자유")], max_length=20, verbose_name="태그"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=50, verbose_name="제목"),
        ),
    ]
