# Generated by Django 4.2.4 on 2023-09-08 06:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("posts", "0005_alter_post_tags_alter_post_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="views",
            field=models.ManyToManyField(
                blank=True,
                related_name="view_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="조회수",
            ),
        ),
    ]
