# Generated by Django 4.2.4 on 2023-08-22 10:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_profile_image_user_short_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="short_description",
        ),
        migrations.AddField(
            model_name="user",
            name="nickname",
            field=models.CharField(default="user", max_length=20),
        ),
    ]
