# Generated by Django 4.2.4 on 2023-09-07 07:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0005_alter_post_tags_alter_post_title"),
        ("users", "0003_remove_user_short_description_user_nickname"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="like_posts",
            field=models.ManyToManyField(
                blank=True,
                related_name="like_users",
                to="posts.post",
                verbose_name="좋아요 목록",
            ),
        ),
    ]
