# Generated by Django 4.2.4 on 2023-09-09 08:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_user_like_posts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="nickname",
            field=models.CharField(default="user<built-in function id>", max_length=20),
        ),
    ]
