# Generated by Django 4.2.4 on 2023-09-09 08:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fridge", "0003_alter_fridge_exp_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fridge",
            name="exp_date",
            field=models.DateTimeField(null=True, verbose_name="유통기한"),
        ),
    ]
