# Generated by Django 4.2.4 on 2023-09-22 17:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fridge", "0007_alter_fridge_exp_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fridge",
            name="exp_date",
            field=models.DateTimeField(default="9999-12-31", verbose_name="유통기한"),
        ),
    ]
