# Generated by Django 4.2.4 on 2023-09-22 17:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fridge", "0010_alter_fridge_exp_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fridge",
            name="exp_date",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(9999, 12, 31, 0, 0),
                verbose_name="유통기한",
            ),
        ),
    ]
